services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mutual-fund-screener:v1.0
    container_name: mutual-fund-screener
    ports:
      - "80:80"
    restart: unless-stopped