EQUITY_DEFAULT_SCREENS = [
    {
        "external_id": "equity-large-cap-core",
        "name": "Equity Large Cap Core",
        "description": "Core large-cap oriented funds with steadier risk and dependable medium-term growth.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Large Cap Fund"]},
                "cagr_3y": {"gte": 11},
                "volatility": {"lte": 16},
                "mdd_three_year_pct": {"lte": 20},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-large-mid-blend",
        "name": "Equity Large & Mid Blend",
        "description": "Large and mid-cap blend funds balancing growth with controlled downside.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Large & Mid Cap Fund"]},
                "cagr_3y": {"gte": 12},
                "cagr_5y": {"gte": 12},
                "mdd_three_year_pct": {"lte": 24},
            },
            "sort_field": "cagr_5y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-mid-cap-momentum",
        "name": "Equity Mid Cap Momentum",
        "description": "Mid-cap funds with stronger growth trend while keeping risk metrics in check.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Mid Cap Fund"]},
                "cagr_3y": {"gte": 14},
                "sharpe": {"gte": 0.8},
                "mdd_three_year_pct": {"lte": 30},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "abs_3m",
                "abs_6m",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-small-cap-growth",
        "name": "Equity Small Cap Growth",
        "description": "Small-cap funds with high return potential and acceptable drawdown profile.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Small Cap Fund"]},
                "cagr_3y": {"gte": 15},
                "cagr_5y": {"gte": 14},
                "sortino": {"gte": 0.7},
                "mdd_three_year_pct": {"lte": 36},
            },
            "sort_field": "cagr_5y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "abs_3m",
                "abs_6m",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-flexi-cap-all-weather",
        "name": "Equity Flexi Cap All Weather",
        "description": "Flexi-cap funds with strong consistency and moderate downside behavior.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Flexi Cap Fund"]},
                "cagr_3y": {"gte": 12},
                "cagr_5y": {"gte": 12},
                "volatility": {"lte": 18},
                "downside_deviation": {"lte": 11},
            },
            "sort_field": "cagr_5y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "downside_deviation",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-multi-cap-diversified",
        "name": "Equity Multi Cap Diversified",
        "description": "Multi-cap funds focused on diversified long-term performance with balanced risk.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Multi Cap Fund"]},
                "cagr_3y": {"gte": 12},
                "sharpe": {"gte": 0.8},
                "volatility": {"lte": 20},
            },
            "sort_field": "sharpe",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-value-contra",
        "name": "Equity Value & Contra",
        "description": "Value and contra styles filtered for favorable medium-term risk-adjusted returns.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Value Fund", "Contra Fund"]},
                "cagr_3y": {"gte": 11},
                "sharpe": {"gte": 0.7},
                "mdd_three_year_pct": {"lte": 28},
            },
            "sort_field": "sharpe",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "equity-index-core",
        "name": "Equity Index Core",
        "description": "Index-oriented equity funds with decent long-term returns and lower volatility preference.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Equity"]},
                "scheme_sub_category": {"in": ["Index Fund"]},
                "cagr_3y": {"gte": 10},
                "volatility": {"lte": 17},
                "mdd_three_year_pct": {"lte": 22},
            },
            "sort_field": "volatility",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
]

DEBT_DEFAULT_SCREENS = [
    {
        "external_id": "debt-liquid-safety",
        "name": "Debt Liquid Safety",
        "description": "Liquid and overnight funds for short-horizon parking with lower drawdown.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Liquid Fund", "Overnight Fund"]},
                "cagr_1y": {"gte": 5},
                "mdd_one_year_pct": {"lte": 1.5},
                "volatility": {"lte": 3},
            },
            "sort_field": "mdd_one_year_pct",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "abs_1m",
                "abs_3m",
                "cagr_1y",
                "volatility",
                "mdd_one_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
    {
        "external_id": "debt-short-duration",
        "name": "Debt Short Duration",
        "description": "Short-duration debt funds with balanced accrual and manageable risk.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {
                    "in": ["Ultra Short Duration Fund", "Low Duration Fund", "Short Duration Fund"]
                },
                "cagr_3y": {"gte": 6},
                "mdd_three_year_pct": {"lte": 7},
                "downside_deviation": {"lte": 4},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "abs_3m",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
    {
        "external_id": "debt-money-market-stable",
        "name": "Debt Money Market Stable",
        "description": "Money market focused debt funds with lower volatility and stable outcomes.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Money Market Fund"]},
                "cagr_1y": {"gte": 5.5},
                "volatility": {"lte": 4},
                "mdd_one_year_pct": {"lte": 2},
            },
            "sort_field": "volatility",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "abs_1m",
                "abs_3m",
                "volatility",
                "mdd_one_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
    {
        "external_id": "debt-corporate-bond-quality",
        "name": "Debt Corporate Bond Quality",
        "description": "Corporate bond funds screened for consistency and improved risk-adjusted returns.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Corporate Bond Fund"]},
                "cagr_3y": {"gte": 6.5},
                "sharpe": {"gte": 0.7},
                "mdd_three_year_pct": {"lte": 9},
            },
            "sort_field": "sharpe",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "abs_6m",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
    {
        "external_id": "debt-banking-psu-accrual",
        "name": "Debt Banking & PSU Accrual",
        "description": "Banking and PSU debt funds targeting accrual with limited downside.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Banking and PSU Fund"]},
                "cagr_3y": {"gte": 6.5},
                "downside_deviation": {"lte": 4.5},
                "mdd_three_year_pct": {"lte": 8},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "downside_deviation",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "debt-gilt-defensive",
        "name": "Debt Gilt Defensive",
        "description": "Gilt funds with a defensive tilt using drawdown and volatility controls.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Gilt Fund"]},
                "cagr_3y": {"gte": 6},
                "volatility": {"lte": 9},
                "mdd_three_year_pct": {"lte": 14},
            },
            "sort_field": "mdd_three_year_pct",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "debt-dynamic-bond-all-weather",
        "name": "Debt Dynamic Bond All Weather",
        "description": "Dynamic bond funds filtered for balanced return and downside management.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Debt"]},
                "scheme_sub_category": {"in": ["Dynamic Bond Fund"]},
                "cagr_3y": {"gte": 6.5},
                "sortino": {"gte": 0.7},
                "mdd_three_year_pct": {"lte": 12},
            },
            "sort_field": "sortino",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "abs_3m",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "mdd_max_drawdown_percent",
                "calmar",
            ],
        },
    },
]

HYBRID_DEFAULT_SCREENS = [
    {
        "external_id": "hybrid-aggressive-growth",
        "name": "Hybrid Aggressive Growth",
        "description": "Aggressive hybrid funds with stronger growth and acceptable downside control.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Aggressive Hybrid Fund"]},
                "cagr_3y": {"gte": 10.5},
                "cagr_5y": {"gte": 10},
                "mdd_three_year_pct": {"lte": 22},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "cagr_1y",
                "cagr_3y",
                "cagr_5y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "hybrid-balanced-consistency",
        "name": "Hybrid Balanced Consistency",
        "description": "Balanced hybrid funds screened for steadier performance and lower volatility.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Balanced Hybrid Fund"]},
                "cagr_3y": {"gte": 8.5},
                "volatility": {"lte": 13},
                "mdd_three_year_pct": {"lte": 16},
            },
            "sort_field": "mdd_three_year_pct",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "downside_deviation",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "hybrid-conservative-defense",
        "name": "Hybrid Conservative Defense",
        "description": "Conservative hybrid allocation with focus on lower risk and drawdown.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Conservative Hybrid Fund"]},
                "cagr_3y": {"gte": 7},
                "volatility": {"lte": 10},
                "mdd_three_year_pct": {"lte": 10},
            },
            "sort_field": "volatility",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "time_since_inception_years",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "downside_deviation",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "hybrid-dynamic-allocation",
        "name": "Hybrid Dynamic Allocation",
        "description": "Dynamic asset allocation funds with balanced return-to-risk profile.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Dynamic Asset Allocation Fund"]},
                "cagr_3y": {"gte": 8.5},
                "sortino": {"gte": 0.8},
                "mdd_three_year_pct": {"lte": 15},
            },
            "sort_field": "sortino",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
    {
        "external_id": "hybrid-equity-savings",
        "name": "Hybrid Equity Savings",
        "description": "Equity savings funds with relatively lower drawdown and stable medium-term returns.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Equity Savings Fund"]},
                "cagr_3y": {"gte": 7.5},
                "volatility": {"lte": 11},
                "mdd_three_year_pct": {"lte": 12},
            },
            "sort_field": "mdd_three_year_pct",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "hybrid-multi-asset",
        "name": "Hybrid Multi Asset",
        "description": "Multi-asset allocation funds targeting diversification and smoother risk-adjusted returns.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Multi Asset Allocation Fund"]},
                "cagr_3y": {"gte": 8.5},
                "sharpe": {"gte": 0.75},
                "mdd_three_year_pct": {"lte": 18},
            },
            "sort_field": "sharpe",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "hybrid-arbitrage-stable",
        "name": "Hybrid Arbitrage Stable",
        "description": "Arbitrage funds prioritizing capital stability and lower volatility.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Hybrid"]},
                "scheme_sub_category": {"in": ["Arbitrage Fund"]},
                "cagr_1y": {"gte": 5.5},
                "volatility": {"lte": 4},
                "mdd_one_year_pct": {"lte": 2},
            },
            "sort_field": "volatility",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "volatility",
                "mdd_one_year_pct",
                "current_drawdown_percent",
                "calmar",
                "downside_deviation",
            ],
        },
    },
]

GOLD_DEFAULT_SCREENS = [
    {
        "external_id": "gold-low-drawdown",
        "name": "Gold Low Drawdown",
        "description": "Gold commodity funds filtered for lower drawdown behavior over 1Y and 3Y.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Commodity"]},
                "scheme_sub_category": {"in": ["Gold"]},
                "mdd_one_year_pct": {"lte": 16},
                "mdd_three_year_pct": {"lte": 22},
            },
            "sort_field": "mdd_one_year_pct",
            "sort_order": "asc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "abs_3m",
                "volatility",
                "mdd_one_year_pct",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "gold-risk-adjusted",
        "name": "Gold Risk Adjusted",
        "description": "Gold-focused screens balancing returns with risk-adjusted ratios.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Commodity"]},
                "scheme_sub_category": {"in": ["Gold"]},
                "cagr_3y": {"gte": 7},
                "sharpe": {"gte": 0.45},
                "sortino": {"gte": 0.55},
            },
            "sort_field": "sharpe",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "silver-core",
        "name": "Silver Core Allocation",
        "description": "Silver commodity funds for growth-oriented satellite commodity exposure.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Commodity"]},
                "scheme_sub_category": {"in": ["Silver"]},
                "cagr_1y": {"gte": 6},
            },
            "sort_field": "cagr_1y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "abs_3m",
                "volatility",
                "mdd_one_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
    {
        "external_id": "commodity-diversified",
        "name": "Commodity Diversified",
        "description": "Commodity basket across gold and silver with focus on balanced risk-return.",
        "filters": {
            "filters": {
                "scheme_class": {"in": ["Commodity"]},
                "scheme_sub_category": {"in": ["Gold", "Silver"]},
                "cagr_3y": {"gte": 6.5},
                "mdd_three_year_pct": {"lte": 28},
            },
            "sort_field": "cagr_3y",
            "sort_order": "desc",
            "enabled_filters": [
                "scheme_sub_category",
                "cagr_1y",
                "cagr_3y",
                "volatility",
                "mdd_three_year_pct",
                "current_drawdown_percent",
                "calmar",
            ],
        },
    },
]

DEFAULT_SCREEN_GROUPS = [
    {"key": "equity", "label": "Equity Focused", "filters": EQUITY_DEFAULT_SCREENS},
    {"key": "debt", "label": "Debt Focused", "filters": DEBT_DEFAULT_SCREENS},
    {"key": "gold", "label": "Gold Focused", "filters": GOLD_DEFAULT_SCREENS},
    {"key": "hybrid", "label": "Hybrid Focused", "filters": HYBRID_DEFAULT_SCREENS},
]

DEFAULT_SCREENS = [
    *EQUITY_DEFAULT_SCREENS,
    *DEBT_DEFAULT_SCREENS,
    *GOLD_DEFAULT_SCREENS,
    *HYBRID_DEFAULT_SCREENS,
]

